### ISSUE TITLE
Eastern Palace - TODO List

### ISSUE THREAD

**Issue by ZeldoRetro** [KaKaShUruKioRa/A-Link-to-the-Past-Project#19]
TODO List for Eastern Palace : 

- [x] Skeleton Room : Revision of the spawning of skeletons
- [ ] Special skelets appears after obtaining the Bow
- [x] Dialogs for the dungeon (Sahasrahla Hint, Dungeon Items, closed Doors and Big Chest)
- [x] Red eyegores : ONLY THE ARROWS
- [ ] Boss : Quand il reste un Armos, il doit regagner tous ses PVs
- [ ] Boss : Sensible au boomerang
