### ISSUE TITLE
TODO List - Global

### ISSUE THREAD

**Issue by ZeldoRetro** [KaKaShUruKioRa/A-Link-to-the-Past-Project#25]
- [ ] Palettes ennemis
- [ ] Effet de chute/eau des ennemis/entités
- [ ] Palettes des tilesets
- [ ] Separator Manager : Faire en sorte de "figer" les ennemis pendant les transitions de pièces
- [ ] Door Manager : Dans certains cas, on ne peut pas avoir de porte qui se referme derrière nous. Trouver une solution (exemple : Hyrule Castle B1)
