### ISSUE TITLE
Desert Palace - TODO List

### ISSUE THREAD

**Issue by ZeldoRetro** [KaKaShUruKioRa/A-Link-to-the-Past-Project#29]
TODO List pour Desert Palace : 

- [x] Comportement des Beamos à corriger
- [x] Il manque des tiles de mur "sali". Merci FF Omega.
- [x] Distance de trigger des sables mouvants trop petite
- [x] Voir si il est possible d'améliorer l'effet de glissement du mur ?
