### ISSUE TITLE
TODO List - Ennemis

### ISSUE THREAD

**Issue by ZeldoRetro** [KaKaShUruKioRa/A-Link-to-the-Past-Project#31]
Ci-dessous la liste du bestiaire de ALTTP globale avec remarques associées : 
_Cette liste contient pour le moments les ennemis du Light World_
Liste complète sur le wiki ici https://zelda.fandom.com/wiki/Enemies_in_A_Link_to_the_Past

**Merci de cocher seulement lorsque les stats (Health/Damage) sont les bonnes !**

- [ ] Soldats simples : semble OK
- [ ] Soldats globaux
- [ ] Chevaliers à fléau : Import du Zeldopack
- [x] Archers : codés par Razdarac
- [ ] Archers dans les herbes
- [ ] Lanceurs de bombes
- [ ] Chevaliers aux poignards : dans la tour du château, fonctionne comme les soldats globaux, mais en plus rapides

- [ ] Armos
- [ ] Abeilles
- [ ] Blobs : Electricité quand on les touche
- [ ] Corbeaux
- [x] Deadrocks
- [ ] Geldman
- [ ] Octorocks
- [ ] Octoballoons
- [ ] Esprits
- [ ] Crabes
- [ ] Tektites
- [ ] Voleurs
- [ ] Vautours
- [ ] Zoras - Stats OK

- [ ] Devalant
- [ ] Eyegores
- [x] Hardhat Beetle
- [x] Kodongos
- [ ] Leevers
- [ ] Moldorm - Stats OK
- [ ] Popos
- [ ] Rats
- [ ] Chauves-souris
- [ ] Serpents
- [ ] Squelettes

- [x] Beamos
- [ ] Bubble
- [x] Bumper
- [ ] Canons
- [ ] Barre de feu (tournante)
