### ISSUE TITLE
TODO List - Objets

### ISSUE THREAD

**Issue by ZeldoRetro** [KaKaShUruKioRa/A-Link-to-the-Past-Project#32]
Ci-dessous la listes des objets de ALTTP : 
Liste complète sur le wiki ici https://zelda.fandom.com/wiki/Items_in_A_Link_to_the_Past

- [x] Épées
- [x] Boucliers
- [x] Tuniques
- [x] Bottes de Pégase
- [x] Gants
- [x] Palmes
- [ ] Perle de Lune
- [x] Arc
- [ ] Flèches d'argent
- [ ] Boomerang
- [x] Grappin
- [x] Bombes
- [ ] Champignon/Poudre magique
- [ ] Baguette de Feu
- [ ] Baguette de Glace
- [ ] Flammes
- [ ] Éther
- [ ] Secousses
- [x] Lanterne
- [ ] Marteau
- [ ] Pelle
- [ ] Flûte
- [ ] Filet à papillons
- [ ] Livre de Mudora
- [ ] Bouteilles
- [ ] Canne de Somaria
- [ ] Canne de Byrna
- [ ] Cape magique
- [ ] Miroir magique
